server:
  port: 8086

spring:
  application:
    name: item-service
  datasource:
    url: jdbc:postgresql://localhost:3030/Auth-db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  pre-loading-enabled: false
