server:
  port: 8084

spring:
  application:
    name: item-service
  datasource:
    # Uses Cloud environment variables if present, otherwise falls back to your local setup
    url: ${DB_URL:jdbc:postgresql://localhost:3030/item-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  pre-loading-enabled: false
