steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'Auth-Service/Auth-Service'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/food-application-prod/food-app-repo/auth-service:$COMMIT_SHA'
      - '.'

images:
  - 'asia-south1-docker.pkg.dev/food-application-prod/food-app-repo/auth-service:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY