server:
  port: 8083

spring:
  application:
    name: menu-service
  datasource:
    # Uses Cloud environment variables if present, otherwise falls back to your local setup
    url: ${DB_URL:jdbc:postgresql://localhost:3030/menu_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
